# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Gideon  Aduku'
description: 'Coffee, Code, Guinness, More Code'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
facebook: 'https://www.facebook.com/gidis88'
twitter: 'https://twitter.com/gideonaduku'
linkedin: 'https://www.linkedin.com/in/gideonaduku/'
instagram: ''
# pinterest: ''
# youtube: ''
github-user: 'https://github.com/adukugideon'
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
# weibo: ''
# vk: ''
blog_url: ''
email: 'gideonaduku@gmail.com'
# messenger: ''

# Advanced settings
plugins:
  - jekyll-remote-theme
